name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-lastest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm i
      - run: npm run build --if-present
      - name: deploy on github page
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
